- README.md
- app/api-v1/README.md
Signed-off-by: kaverikhaneja <kaveri.khaneja@accenture.com>
**Changelog**
- Updated the README.md files with instructions to run the express app.
> Updated API README

- app/api-v1/controllers/Order/__tests__/helpers.test.js
- app/api-v1/controllers/Order/helpers.js
- app/api-v1/controllers/Order/index.js
- app/api-v1/controllers/Recipe/helpers.js
Summary
Passing ownership of token based on order actions
> Infra 143- passing ownership based on order actions

- .eslintrc
- app/api-v1/controllers/Order/index.js
Summary
logging to see runprocess payload
> Infra 143 - adding logs

- .eslintrc
- app/api-v1/controllers/Order/__tests__/orders.test.js
- app/api-v1/controllers/Order/index.js
Summary 
fixing typo - changing req to req.body for accessing body parameters and mocking getorder to return items
> Infra 143 -  fixing typo

- app/api-v1/controllers/Order/helpers.js
not creating token ids for recipes when accepting an order
> not creating new recipe tokens when accepting an order

- app/api-v1/api-doc.js
- app/api-v1/controllers/Build/helpers.js
- app/api-v1/controllers/Build/index.js
- app/api-v1/controllers/Order/index.js
- app/api-v1/routes/build/{id}/start.js
- app/api-v1/routes/order/{id}/acknowkedgement/{acknowledgementid}.js
- app/api-v1/routes/order/{id}/acknowledgement.js
**Summary**
Adding build start endpoint
> INFRA-102 adding build start endpoint

- app/api-v1/routes/build/{id}/start.js
- app/api-v1/routes/build/{id}/start/{startId}.js
Summary
fixing build start(GET) endpoint
> fixing build start get

- app/api-v1/controllers/Build/index.js
Summary
Adding progress update GET endpoint
> adding get progress update endpoint

- migrations/20220826092757_add_enum_progress-update.js
**Summary**
Adding progress-update  to enum type
> Fixing build transaction type enum

- app/api-v1/controllers/Build/index.js
- app/api-v1/routes/build/{id}/completion.js
- app/api-v1/routes/build/{id}/completion/{completionId}.js
- app/api-v1/routes/build/{id}/progress-update.js
- app/api-v1/routes/build/{id}/progress-update/{updateId}.js
**Summary**
Adding build completion endpoint
> adding build completion endpoint

- app/api-v1/routes/build/{id}/completion.js
**Summary**
adding type of build while build completion
> adding type of build while build completion

- app/api-v1/controllers/Build/index.js
- app/api-v1/routes/build/{id}/completion.js
- app/api-v1/routes/build/{id}/completion/{completionId}.js
- migrations/20220809103019_build.js
- migrations/20220822113458_build_transactions.js
**Summary**
changing build status from submitted to completed
> changing build status from submitted to completed

- app/api-v1/controllers/Build/helpers.js
- app/api-v1/controllers/Build/index.js
**Summary**
passing image to chain for build completion and progress update
> passing image to chain for build completion and progress update

- app/api-v1/controllers/Build/helpers.js
**Summary**
Adding image value in metadata
> adding image value in metadata

- app/api-v1/api-doc.js
- app/api-v1/controllers/Build/__tests__/builds.test.js
- app/api-v1/controllers/Build/helpers.js
- app/api-v1/controllers/Build/index.js
- migrations/20220809103019_build.js
- test/seeds/build.js
**Summary**
Changing variable completion_estimated_at to completion_estimate
> changing completion_estimated_at to completion_estimate

- app/api-v1/controllers/Part/__tests__/parts.test.js
- app/api-v1/controllers/Part/index.js
- app/db/index.js
**Summary**
Adding part GET endpoint
> adding part GET endpoint

- app/api-v1/controllers/Build/__tests__/builds.test.js
- app/api-v1/controllers/Build/index.js
**Summary**
Adding certifications to parts
> adding certifications to parts

- app/api-v1/controllers/Attachment/helpers.js
- app/api-v1/controllers/Attachment/index.js
- app/api-v1/controllers/Build/helpers.js
- app/api-v1/controllers/Build/index.js
- app/api-v1/controllers/Order/helpers.js
- app/api-v1/controllers/Order/index.js
- app/api-v1/controllers/Part/helpers.js
- app/api-v1/controllers/Part/index.js
- app/api-v1/controllers/Recipe/helpers.js
- app/db/index.js
- app/server.js
- test/integration/docs.test.js
**Summary**
Refactoring code according to sonarqube feedback
> Refactoring

- app/api-v1/controllers/Build/helpers.js
- app/api-v1/controllers/Build/index.js
- app/api-v1/controllers/Order/helpers.js
- app/api-v1/controllers/Order/index.js
- app/api-v1/controllers/Part/helpers.js
- app/api-v1/controllers/Part/index.js
**Summary**
Removing duplicates
> removing duplicates

- app/api-v1/api-doc.js
- app/api-v1/controllers/Order/__tests__/orders.test.js
- app/api-v1/controllers/Order/index.js
- app/api-v1/routes/order/{id}/acknowkedgement/{acknowledgementId}.js
- app/api-v1/routes/order/{id}/acknowkedgement/{acknowledgementid}.js
- app/api-v1/routes/order/{id}/acknowledgement.js
- app/api-v1/routes/order/{id}/cancellation/{cancellationId}.js
**Summary**
- changed path params from rejectionId to acknowledgementId'
- Renamed filename from acknowledgementid to acknowledgementId
> changed path params from rejectionId to acknowledgementId

- app/api-v1/controllers/Build/__tests__/builds.test.js
- app/api-v1/controllers/Order/__tests__/orders.test.js
- app/api-v1/controllers/Order/index.js
- app/api-v1/controllers/Recipe/__tests__/recipe.test.js
- test/integration/build.test.js
- test/integration/order.test.js
- test/integration/recipe.test.js
- test/seeds/build.js
- test/seeds/orders.js
**Summary**
- Adding unit and integration test for order and recipe
> adding unit and integration tests for order and recipe

- app/api-v1/api-doc.js
- app/api-v1/controllers/Order/index.js
- app/api-v1/routes/order/summary.js
**Summary**
- Adding order summary endpoint
> adding order summary endpoint

- app/api-v1/controllers/Build/helpers.js
- app/api-v1/controllers/Order/helpers.js
- app/api-v1/controllers/Order/index.js
- test/integration/build.test.js
- test/integration/order.test.js
- test/integration/recipe.test.js
**Summary**
- Fixing order history endpoint
> fixing order history endpoint

- app/api-v1/api-doc.js
- app/api-v1/controllers/Order/helpers.js
- app/api-v1/controllers/Part/helpers.js
- app/api-v1/controllers/Part/index.js
- app/api-v1/routes/part/{id}/update-delivery-date.js
- migrations/20221108142822_adding_delivery_update_type.js.js
**Summary** 
- adding  update delivery date endpoint
> adding  update delivery date endpoint

- app/api-v1/controllers/Part/helpers.js
- app/api-v1/controllers/Part/index.js
- migrations/20221109170954_adding_part_received_status.js.js
**Summary**
- adding metadata for goods receipt
> adding metadata for goods receipt

- app/api-v1/api-doc.js
- app/api-v1/controllers/Build/helpers.js
- app/api-v1/controllers/Order/__tests__/orders.test.js
- app/api-v1/controllers/Order/helpers.js
- app/api-v1/controllers/Order/index.js
- app/api-v1/controllers/Part/helpers.js
- app/api-v1/controllers/Recipe/index.js
**Summary**
- Returning order history in correct format
- Returning order/build updatedAt in get order
- Returning part requiredBy in get order
> returing order history in correct format

- app/api-v1/api-doc.js
- app/api-v1/controllers/Build/index.js
- app/api-v1/controllers/Order/__tests__/orders.test.js
- app/api-v1/controllers/Order/helpers.js
- app/api-v1/controllers/Order/index.js
- app/api-v1/controllers/Recipe/index.js
- app/db/index.js
**Summary**
- Adding build external id in order get
- Checking for duplicate external id
> adding build external id in order get

- app/api-v1/api-doc.js
- app/api-v1/controllers/Build/index.js
- app/api-v1/controllers/Order/index.js
**Summary**
- Retuning order history according to new schema
> returning order history based on new schema

- app/api-v1/api-doc.js
- app/api-v1/controllers/Order/index.js
**Summary**
- adding job external id and id in order history
- sorting history by submittedAt
> adding job external id and id in order history

- app/api-v1/controllers/Order/index.js
**Summary**
- Fixing typo in requiredBy
- throwing error if order not found
> fixing type in requiredBy

- app/api-v1/api-doc.js
- app/api-v1/controllers/Build/helpers.js
- app/api-v1/controllers/Build/index.js
- app/api-v1/controllers/Order/helpers.js
- app/api-v1/controllers/Order/index.js
- app/api-v1/controllers/Part/helpers.js
- app/api-v1/controllers/Part/index.js
- app/api-v1/routes/build/{id}.js
- app/api-v1/routes/order/{id}.js
- app/api-v1/routes/part/{id}.js
- app/db/index.js
- migrations/20221121145226_adding_ownership_type.js.js
**Summary**
- passing token ownership of part when GRN uploaded
> passing token ownership of part when GRN uploaded

- app/api-v1/controllers/Build/index.js
- app/api-v1/controllers/Order/index.js
- app/api-v1/controllers/Part/index.js
- app/api-v1/controllers/Recipe/index.js
**Summary**
- returning error when there is no token ownership
> returning error when there is no token ownership

- app/api-v1/controllers/Order/index.js
- app/api-v1/routes/order.js
**Summary**
- returning response for external id as same as by id
> returning response for external id as same as by id

- app/api-v1/api-doc.js
- app/api-v1/controllers/Build/index.js
- app/api-v1/controllers/Order/__tests__/orders.test.js
- app/api-v1/controllers/Order/helpers.js
- migrations/20221128105441_adding_complete_status_to_order.js
**Summary**
- Setting order status to Completed when build status is Part Received
> Order complete status (INFRA-267)

- helm/inteli-api/Chart.yaml
- helm/inteli-api/values.yaml
- package-lock.json
- package.json
> bump versions

- .github/workflows/tests.yml
- app/api-v1/controllers/Build/helpers.js
- app/api-v1/controllers/Build/index.js
- app/api-v1/controllers/Order/index.js
- app/api-v1/controllers/Part/index.js
- app/api-v1/controllers/Recipe/index.js
**Summary**
- Adding 3-way match complete progress update
> adding 3-way match complete progress update

- app/api-v1/controllers/Part/helpers.js
- app/utils/dscp-api/index.js
**Summary**
- making delivery address and line text accept more than 32 characters
> making delivery address and line text accept more than 32 characters

- app/api-v1/api-doc.js
- app/api-v1/controllers/Order/index.js
**Summary**
- adding confirmed receipt date in order history endpoint
> adding confirmed receipt date in order history endpoint

- app/api-v1/api-doc.js
- app/api-v1/controllers/Part/helpers.js
**Summary**
- adding buyer info in part get
> adding buyer info in part get

- app/api-v1/controllers/Order/index.js
- app/db/index.js
**Summary**
- added pagination for order and recipe
> added pagination for order and recipe

- app/server.js
**Summary**
- disabling timeout
> disabling timeout

- app/api-v1/api-doc.js
- app/api-v1/controllers/Order/index.js
**Summary**
- correcting order summary count (INFRA-321)
> correcting order summary count

- app/api-v1/controllers/Order/index.js
- app/db/index.js
**Summary**
- search order by external id / id pattern
> search order by external id / id pattern

- app/db/index.js
**Summary**
- Fixing typo in whereilike
> fixing typo

- app/api-v1/controllers/Recipe/index.js
- app/db/index.js
**Summary**
- adding seach functionality for planned order
> adding search functionality for planned order

- app/api-v1/controllers/Build/__tests__/builds.test.js
- app/api-v1/controllers/Build/index.js
- app/api-v1/controllers/Part/index.js
- app/db/index.js
**Summary**
- search by job/part number
> search by job/part number

- app/db/index.js
**Summary**
- searching job number part number using order
> searching job number part number using order

- app/api-v1/api-doc.js
- app/api-v1/controllers/MachiningOrder/helpers.js
- app/api-v1/controllers/MachiningOrder/index.js
- app/api-v1/controllers/Part/index.js
- app/api-v1/routes/machiningOrder.js
- app/api-v1/routes/machiningOrder/{id}.js
- app/api-v1/routes/machiningOrder/{id}/accepted.js
- app/api-v1/routes/machiningOrder/{id}/accepted/{acceptedId}.js
- app/api-v1/routes/machiningOrder/{id}/complete/{completeId}.js
- app/api-v1/routes/machiningOrder/{id}/completion.js
- app/api-v1/routes/machiningOrder/{id}/partShipped.js
- app/api-v1/routes/machiningOrder/{id}/partShipped/{partShippedId}.js
- app/api-v1/routes/machiningOrder/{id}/start.js
- app/api-v1/routes/machiningOrder/{id}/start/{startid}.js
- app/api-v1/routes/machiningOrder/{id}/submission.js
- app/api-v1/routes/machiningOrder/{id}/submission/{submissionId}.js
- app/db/index.js
- app/utils/dscp-api/index.js
- migrations/20230222143046_machining_order.js
- migrations/20230224134334_machine_order_transactions.js
**Summary**
- added machining order object
> added machining order object

- app/api-v1/api-doc.js
- app/api-v1/controllers/MachiningOrder/helpers.js
- app/api-v1/controllers/MachiningOrder/index.js
- app/db/index.js
**Summary**
- added pagination, filtering and returning task number for MO (INFRA-375)
> added pagination, filtering and returning task number for MO (INFRA-375)

- app/api-v1/api-doc.js
- app/api-v1/controllers/MachiningOrder/index.js
- app/api-v1/routes/machiningOrder/count.js
- app/db/index.js
**Summary**
- adding mo count and search by external id functionality
> adding mo count and search by external id functionality

- app/api-v1/api-doc.js
- app/api-v1/controllers/MachiningOrder/helpers.js
- app/api-v1/controllers/MachiningOrder/index.js
- app/api-v1/routes/machiningOrder/{id}/history.js
**Summary**
- returning the result as an object and not array and adding MO history
> returning the result as an object and not array

- app/api-v1/routes/machiningOrder.js
**Summary**
- changing get schema for machining order
> changing get schema for machining order

- app/api-v1/api-doc.js
- app/api-v1/controllers/Order/helpers.js
**Summary**
- adding MO external id in order get
> adding MO external id in order get

- app/api-v1/api-doc.js
- app/api-v1/controllers/MachiningOrder/helpers.js
- app/api-v1/controllers/MachiningOrder/index.js
**Summary**
- removing task number
> removing task number

- app/db/index.js
**Summary**
- searching for machining order by job number
> searching for machining order by job number

- app/api-v1/api-doc.js
- app/api-v1/controllers/Notification/index.js
- app/api-v1/controllers/Notifications/index.js
- app/api-v1/routes/notification.js
- app/api-v1/routes/notifications.js
- app/db/index.js
- migrations/20230413091227_notifications.js
- migrations/20230413093649_read_delete_notification.js
**Summary**
- added notifications endpoints
> added notifications endpoints

- app/api-v1/api-doc.js
- app/api-v1/controllers/Notifications/index.js
- app/api-v1/routes/notifications/count.js
- app/db/index.js
- app/server.js
**Summary**
- Getting read and un-read notifications
- Getting notifications in descending order based on created time
- Getting notifications count
> Read unread notifications

- app/api-v1/controllers/Notifications/index.js
- app/db/index.js
**Summary**
- grouping notifications based on orderId
> grouping notifications based on orderId

- app/api-v1/controllers/Notifications/index.js
**Summary**
- getting group count
> getting group count

- app/api-v1/api-doc.js
- app/api-v1/controllers/Notifications/index.js
- app/api-v1/routes/notifications.js
- app/db/index.js
**Summary**
- post call for marking read and delete
> post call for marking read and delete

- app/api-v1/controllers/Notifications/index.js
- app/db/index.js
**Summary**
- getting count of read and unread notifications
> getting count of read and unread notifications

- app/api-v1/api-doc.js
- migrations/20230425103312_changing-uuid-to-string.js
**Summary**
- adding new columns to table notifications
> adding new columns to table notifications

- app/api-v1/controllers/Notifications/index.js
- app/db/index.js
**Summary**
- searching notifications by order external id
> searching notifications by order external id

- app/db/index.js
**Summary**
- ordering search result for notifications by order id
> ordering search result for notifications by order id

- app/api-v1/controllers/Part/helpers.js
- app/utils/dscp-api/index.js
**Summary**
- removing character limit on part description
> removing character limit on part description

- app/api-v1/api-doc.js
- app/api-v1/controllers/Build/index.js
- app/api-v1/controllers/MachiningOrder/index.js
- app/api-v1/controllers/Order/__tests__/orders.test.js
- app/api-v1/controllers/Order/index.js
- app/api-v1/controllers/Part/index.js
- app/api-v1/controllers/Recipe/__tests__/recipe.test.js
- app/api-v1/controllers/Recipe/index.js
- app/db/index.js
**Summary**
- removing orders if it fails to save to chain
- removing the check for recipe name length
> removing orders if it fails to save to chain

- app/api-v1/controllers/Notification/index.js
- app/api-v1/routes/notification.js
- app/utils/auth.js
**Summary**
- added authentication for notification api
> added authentication for notification api
